---
- name: Deploy Web Server
  hosts: webservers
  become: true
  tasks:
    - name: Install Nginx
      apt:
        name: nginx
        state: present

    - name: Configure Nginx to Listen on Port 8080
      lineinfile:
        path: /etc/nginx/sites-available/default
        regexp: "listen 80 default_server;"
        line: "listen 8080 default_server;"

    - name: Set Custom Web Page
      copy:
        dest: /var/www/html/index.html
        content: "<h1>Hello World from SJSU-{{ inventory_hostname[-1] }}-(Sanjushree)</h1>"

    - name: Restart Nginx
      service:
        name: nginx
        state: restarted
